In [1]:
import numpy as np

In [4]:
# code to create one dimensional array
a = [1,2,3,4]
x = np.array(a)
print(x)

[1 2 3 4]


In [5]:
type(x)

numpy.ndarray

In [7]:
# creating a 2dimensional array

y = np.array([[1,2,3,4],[4,5,6,7]])
print(y)

[[1 2 3 4]
 [4 5 6 7]]


In [8]:
# to bring the dimenson of th array 
y.shape

(2, 4)

## built in fuction 
+ arange
+ reshape it is used to change the dimension of an array do that they can both be the same dimension
+ shape

In [10]:
value =  np.arange(20)
print(value)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [11]:
# reshape

value =  np.arange(15)
print(value)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [12]:
value.reshape(-1, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [13]:
# the dimension you are reshappping it into must be a multiple of 15
value.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
num = np.arange(16)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
num.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
num.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [18]:
# creating zero values : it gives a column and a row of the specified dimension
zero_value = np.zeros((2,3))
zero_value

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# creating a ones value :
ones = np.ones((2,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
# creating a full value of the specified variable outside the dimension
full_value = np.full((3,3),4)
full_value

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [23]:
# creating an eye value this produce an horizontal values of one
eye_value = np.eye(3,3)
eye_value

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
# numpy math function

x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,2,2],[3,3,3]])
z = np.array([1,2,3])

In [25]:
# Addition of array
print(np.add(x,y))

[[3 4 5]
 [7 8 9]]


In [27]:
# subtraction of array
print(np.subtract(x,y))

[[-1  0  1]
 [ 1  2  3]]


In [28]:
# multiplication of array
print(np.multiply(x,y))

[[ 2  4  6]
 [12 15 18]]


In [29]:
print(x*y)

[[ 2  4  6]
 [12 15 18]]


## Pandas

In [30]:
# it store  our data into data structures
# import pandas
import pandas as pd

In [31]:
# initialize list of lists
data = [['math', 10], ['english' , 15], ['history' , 14]]
print(data)

[['math', 10], ['english', 15], ['history', 14]]


In [33]:
# initialize list of lists
data = [['math', 10], ['english' , 15], ['history' , 14]]
print(data)
# Create the pandas DataFrame from the list and adding column headers
df = pd.DataFrame (data, columns = ['Subject', 'Score'])
# print dataframe.
df

[['math', 10], ['english', 15], ['history', 14]]


Subject  Score
0     math     10
1  english     15
2  history     14

In [34]:
# initialize list of lists
data = {'Subject': ['Math', 'English' ,'History' ] ,'Score':[10, 15, 14]}
# Create the pandas DataFrame from the list and adding column headers
df = pd.DataFrame (data)
# print dataframe.
df

Subject  Score
0     Math     10
1  English     15
2  History     14